### ISSUE TITLE
Blurry canvas when zooming in

### ISSUE THREAD

**Issue by aerosmith** [Nikke-db/nikke-db-vue#38]
When zooming in with the mouse wheel, the image becomes blurry. It wasn't always like this as far I remember. I think this started to happen around January.
Is it because of how zooming is implemented (css scaling)?

I've attached a screenshot of how it is now (image 1) and how it was before (image 2).

![rapi_1](https://github.com/Nikke-db/nikke-db-vue/assets/1782115/824ece20-9d82-4357-9946-21432f440f67)

![rapi_2](https://github.com/Nikke-db/nikke-db-vue/assets/1782115/13b15fbe-149e-4c31-886f-4b4d3ebd14ab)

**Comment by Koshirei** [comment]
Hi. the website uses a hand made zooming system because I'm using spine player and not spine webgl. 
to be honest I have no idea how to make a good zooming system so I've often found myself in situations with an issue or another.
around january indeed I have been made aware of some issues where assets were cropped in monitors using a 2k resolution or higher, and it eventually had to repercutate how the zooming works.
I have though of a potential way to scale the asset better but I never found time to test it out. I will try to work on it this week end a bit

**Comment by Koshirei** [comment]
high and low quality settings have been added in f27e6ee . please let me know if that's good for you, though I'm not sure I'll be able to make something better

**Comment by aerosmith** [comment]
Oh yeah this is actually perfect. Thank you!

I'll close this.
